### ISSUE TITLE
Upgrade Kafka to 0.11.0.0

### ISSUE THREAD

**Issue by datafibers** [datafibers-community/df_data_service#103]
- Upgrade to latest Kafka 0.11.0.0 runtime
- Upgrade flink kafka connector to 0.11.0.0
- Update to use new kafka admin client and remove zkclient

The new pom is as follows:

<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>kafka_2.11</artifactId>
    <version>0.11.0.0</version>
</dependency>

**Comment by willddy** [comment]
updated

**Comment by willddy** [comment]
tested
