### ISSUE TITLE
Support default value for connector.calss

### ISSUE THREAD

**Issue by datafibers** [datafibers-community/df_data_service#110]
connector.calss attribute in connectorConfig is used for Kafka connect. Right now, it requires manually input. We'll map it according to connectType ease case usage. Note, make it to allow overwrite. 

The scenarios are as follows.
- if user specify the class, use it
- If user does not input class, use default one
- remove it from default attribute
- this applies to the connect only

**Comment by datafibers** [comment]
@SchubertZhu , pls. test it

**Comment by willddy** [comment]
tested

**Comment by datafibers** [comment]
released
