### ISSUE TITLE
Submit Flink job through rest api

### ISSUE THREAD

**Issue by willddy** [datafibers-community/df_data_service#116]
Right now, we use Flink java api to submit job and cancel job through rest API. This cause exception in the client side. We'll refractory the code to submit job through [Rest API of Flink](https://ci.apache.org/projects/flink/flink-docs-release-1.3/monitoring/rest_api.html#submitting-programs) for instead.

**Comment by datafibers** [comment]
tested and wait for merge

**Comment by datafibers** [comment]
merged close
