### ISSUE TITLE
Add default value to all certified connect

### ISSUE THREAD

**Issue by datafibers** [datafibers-community/df_data_service#133]
All new kafka connect v0.11.0.0 requires default value to pass validation if you do not specify. We need to add such value. Or else, the connect creation is failed because of missing properties.

define(java.lang.String name, ConfigDef.Type type, java.lang.Object defaultValue, ConfigDef.Importance importance, java.lang.String documentation, java.lang.String group, int orderInGroup, ConfigDef.Width width, java.lang.String displayName, java.util.List<java.lang.String> dependents, ConfigDef.Recommender recommender)

**Comment by willddy** [comment]
tested
