### ISSUE TITLE
Add pause, resume, and restart button to the connect in ui

### ISSUE THREAD

**Issue by willddy** [datafibers-community/df_data_service#140]
Right now, to pause, resume, and restart has to through create and delete rest api. We are looking for such functions in ui as new actions to have better connect admin.

- [x] Pause/Stop
- [x] Resume
- [x] Restart - This is actually update connector bypass chang detection check

**Comment by datafibers** [comment]
@SchubertZhu ready for test

**Comment by datafibers** [comment]
tested, merged close
