### ISSUE TITLE
Kafka avro consumer seems stuck

### ISSUE THREAD

**Issue by willddy** [datafibers-community/df_data_service#150]
Kafka avro consumer seems stuck in low end machine. Its timeout will block the edit view. Following tow actions.
- Consider to use other consumer (NOT)
- Use Show View button inside of the Edit view in the schema list to preview data only. As result, it will not impact EDIT link.

**Comment by willddy** [comment]
done. We did UI update only by creating consumer view/show

**Comment by datafibers** [comment]
released
