### ISSUE TITLE
When connectConfig supports multiple default, all content comes to json body

### ISSUE THREAD

**Issue by datafibers** [datafibers-community/df_data_service#34]
when we use below function to map different default value to the same field entity, all enties are sent. We see both connectorConfig and connectorConfig_2 are in the json body

> myApp.config(function(RestangularProvider) {
>     RestangularProvider.addElementTransformer('posts', function(element) {
>         element.connectorConfig_2 = element.connectorConfig;
>         return element;
>     });
> });

**Comment by willddy** [comment]
added a #41
