### ISSUE TITLE
Redesign connect name in POPJ

### ISSUE THREAD

**Issue by willddy** [datafibers-community/df_data_service#58]
Right now, connect is imputed by user. However, it must be unique. In addition, we need an additional attribute can be referenced in connect for meta information delivery.
- [x] Assign mongodb new ObjectId() as connect/transform, which is like uid
- [x] Refactory taskId to taskSeq
- [x] Refactory connect to connectUid
- [x] Add JobUID to POPJ, default 'NOT_ASSIGNED'
- [x] Inject a cid attribute which is the alias for name in connectConfig
- [x] When add connect to mongo, reuse this I'd instead of new generation
_Id = connectUID = connectConfig.name = connectConfig.cid
- [x] Update certified connect will use this cid in meta data message as pk
- [x] Update UDF Jar name to use ObjectID #61

**Comment by datafibers** [comment]
@SchubertZhu UDF file name can also use such kind of id so that task will have relation of JAR file. Once the jar file task is deleted, we'll remove the jar file as well

**Comment by datafibers** [comment]
IN test
