### ISSUE TITLE
Add -- debug or -d to CLI for DF jar launch 

### ISSUE THREAD

**Issue by willddy** [datafibers-community/df_data_service#70]
* Add -- debug or -d to CLI to enable log4j debug level
* Change default to INFO level

**Comment by datafibers** [comment]
tested

**Comment by SchubertZhu** [comment]
Hi Will,

I check out latest DF code and run it, but get the following exception.

What's the port 8083 for? Look like it is refused to be connected.

I have started  ./df_env_distributed_start_avro_hdp_hive_flink.sh, and
having the following services running:

1440 NameNode
2336 RunJar
2337 RunJar
1521 QuorumPeerMain
2594 Jps
2024 JobManager
1481 DataNode
2570 jar
2332 TaskManager




2016-12-25 02:45:01 INFO  CLIParser:83 - Starting both DataFibers Service
and Web UI ...
2016-12-25 02:45:01 INFO  DFInitService:40 - *********Start DataFibers
Services Completed :)
2016-12-25 02:45:02 INFO  DFWebUI:31 - Web Admin Console is started @
http://packer-virtualbox-iso-1467827111/127.0.1.1:8000/admin/
2016-12-25 02:45:02 DEBUG DFDataProcessor:169 - Distribute
/home/vagrant/df-data-service-1.1-SNAPSHOT-fat.jar to Apache Flink cluster
at localhost:6123
2016-12-25 02:45:02 INFO  DFDataProcessor:660 - Starting initial import
data from Kafka Connect REST Server.
2016-12-25 02:45:03 ERROR DFDataProcessor:749 - Importing from Kafka
Connect Server exception
com.mashape.unirest.http.exceptions.UnirestException:
org.apache.http.conn.HttpHostConnectException: Connect to localhost:8083
[localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
        at
com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
        at
com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
        at
com.datafibers.service.DFDataProcessor.importAllFromKafkaConnect(DFDataProcessor.java:666)
        at
com.datafibers.service.DFDataProcessor.start(DFDataProcessor.java:184)
        at
io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
        at
io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
        at
io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)

Thanks,

Schubert

**Comment by SchubertZhu** [comment]
Look like it is kafka rest port 8083 - I have stopped all the services, and
running the clean up (./df_clean_up_all.sh and ./df_init_all.sh), restart
the command ./df_env_distributed_start_avro_hdp_hive_flink.sh, and check
there are the following services up:

2913 DataNode
3778 TaskManager
2868 NameNode
3094 SchemaRegistryMain
3782 RunJar
3783 RunJar
3785 ConnectDistributed
3913 Jps
3036 SupportedKafka
3469 JobManager
2958 QuorumPeerMain

Kafka has been started up and seen above, but still see the same error.

Any idea?

Thanks,

Schubert

**Comment by willddy** [comment]
The 8083 is kafka connect rest server. You should check the log at /mnt/log

**Comment by SchubertZhu** [comment]
Hi Will,

I have attached all the log files from /mnt/log folder. I check the log
files, don't see helpful information.

Why does Kafka REST API cannot be connected? Kafka service has been started
successfully. As you can see below:


2913 DataNode
3778 TaskManager
2868 NameNode
3094 SchemaRegistryMain
3782 RunJar
3783 RunJar
3785 ConnectDistributed
3913 Jps
3036 SupportedKafka
3469 JobManager
2958 QuorumPeerMain

**Comment by willddy** [comment]
Kafka connect is an separate service.
You should check the distributeKafkaconnect.log

**Comment by SchubertZhu** [comment]
See the following error from

 (org.apache.kafka.connect.runtime.distributed.DistributedConfig:178)
[2016-12-25 04:16:02,512] INFO Logging initialized @864ms
(org.eclipse.jetty.util.log:186)
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed
to construct kafka consumer
at org.apache.kafka.connect.runtime.distributed.WorkerGroupMember.<init>(
WorkerGroupMember.java:125)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.<init>(
DistributedHerder.java:148)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.<init>(
DistributedHerder.java:130)

**Comment by SchubertZhu** [comment]
See the following error from file distributeKafkaconnect.log; any way to
fix the issue?

 (org.apache.kafka.connect.runtime.distributed.DistributedConfig:178)
[2016-12-25 04:16:02,512] INFO Logging initialized @864ms
(org.eclipse.jetty.util.log:186)
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed
to construct kafka consumer
at org.apache.kafka.connect.runtime.distributed.WorkerGroupMember.<init>(
WorkerGroupMember.java:125)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.<init>(
DistributedHerder.java:148)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.<init>(
DistributedHerder.java:130)

**Comment by SchubertZhu** [comment]
==> Test to inject avro data from a folder (which contains multiple json
files) to a topic "test", and then to an output topic "finance22":
Preparation:
- Prepare the json/csv files in the specified folder (defined in
file.location=/home/vagrant/ of UI or
connect-file-generic-source.properties)
- Define the proper settings in both quickstart-hdfs.properties and
connect-file-generic-source.properties;
- Make sure they have the same setting of topic=stock in the above two
files;
- The JSON file data columns have to match to schema definition in step 2);
- For CSV file, extra columns in the CSV file will be ignored


1) ./df_env_distributed_start_avro_hdp_hive_flink.sh
2) Make sure the following schema is created before launch loading generic
file connector:


curl -X POST -i -H "Content-Type: application/vnd.schemaregistry.v1+json"
--data '{"schema": "{ \"type\": \"record\",\"name\":
\"test\",\"fields\":[{\"name\": \"time\", \"type\": \"string\"},{\"name\":
\"symbol\", \"type\": \"string\"}, {\"name\": \"name\", \"type\":
\"string\"}, {\"name\": \"exchange\", \"type\": \"string\"}, {\"name\":
\"open_price\", \"type\": \"string\"}]}"}'
http://localhost:8081/subjects/test-value/versions


4) If you cannot make sure launch loading generic file connector before the
above schema is created, ctrl+C to stop the step 2), and then manually run
the following command:
-- /opt/confluent/bin/connect-standalone connect-avro-standalone.properties
quickstart-hdfs.properties connect-file-generic-source.properties
/opt/confluent/bin/connect-distributed
$CURRENT_DIR/df_config/connect-avro-distributed.properties 1>>
/mnt/logs/distributedkafkaconnect.log 2>>
/mnt/logs/distributedkafkaconnect.log &

5) Create new json files (whcih compliant to the schema above) under folder
/home/vagrant (which is specified in the file
connect-file-generic-source.properties: file.location=/home/vagrant/);

===> The JSON file data columns have to match to schema definition in item
2) above.


6) Use the following to check the json file content is read to the specific
topic "stock" (which is defined in UI by creating a connector
CONNECT_KAFKA_SOURCE_AVRO) (file connect-file-generic-source.properties:
topic=test):

kafka-avro-console-consumer --new-consumer --bootstrap-server
localhost:9092 --topic stock --from-beginning

7) The contents from topic "stock" should be written to the hdfs folder
"/home/vagrant/topics" (which is defined in file
quickstart-hdfs.properties: topics.dir=/home/vagrant/topics), and then
written to hive table "test_hdfs".

8) Use the following commands to check the data in corresponding topics:

kafka-avro-console-consumer  --zookeeper localhost:2181 --topic stock
--from-beginning    (topic name is stock if defined the job through UI)
kafka-avro-console-consumer  --zookeeper localhost:2181 --topic df_meta
--from-beginning

Topic Stock messages:
{"time":"2016-07-28 10:40:31","symbol":"BABA","name":"Alibaba Group Holding
Limited A","exchange":"NYQ","open_price":"83.46"}
{"time":"2016-07-28 10:40:31","symbol":"GOOG","name":"Alphabet
Inc.","exchange":"NMS","open_price":"745.48"}
{"time":"2016-07-28 10:40:31","symbol":"AAPL","name":"Apple
Inc.","exchange":"NMS","open_price":"102.83"}
{"time":"2016-07-28 10:40:31","symbol":"HDP","name":"Hortonworks,
Inc.","exchange":"NMS","open_price":"11.45"}
{"time":"2016-07-28 10:40:31","symbol":"DATA","name":"Tableau Software,
Inc. Class A ","exchange":"NYQ","open_price":"57.08"}
{"time":"2016-07-28 10:40:31","symbol":"YHOO","name":"Yahoo!
Inc.","exchange":"NMS","open_price":"38.58"}
{"time":"2016-07-28 10:40:31","symbol":"NTDOY","name":"NINTENDO CO LTD
ADR","exchange":"PNK","open_price":"25.24"}
{"time":"2016-07-28 10:40:31","symbol":"NTDOY","name":"NINTENDO CO LTD
ADR","exchange":"PNK","open_price":"25.24"}

{"time":"1","symbol":"Eldon Base for stackable storage shelf,
platinum","name":"Muhammed MacIntyre","exchange":"3","open_price":"-213.25"}
{"time":"2","symbol":"1.7 Cubic Foot Compact \"Cube\" Office
Refrigerators","name":"Barry French","exchange":"293","open_price":"457.81"}
{"time":"3","symbol":"Cardinal Slant-D� Ring Binder, Heavy Gauge
Vinyl","name":"Barry French","exchange":"293","open_price":"46.71"}
{"time":"4","symbol":"R380","name":"Clay
Rozendal","exchange":"483","open_price":"1198.97"}
{"time":"5","symbol":"Holmes HEPA Air Purifier","name":"Carlos
Soltero","exchange":"515","open_price":"30.94"}
{"time":"6","symbol":"G.E. Longer-Life Indoor Recessed Floodlight
Bulbs","name":"Carlos Soltero","exchange":"515","open_price":"4.43"}
{"time":"7","symbol":"Angle-D Binders with Locking Rings, Label
Holders","name":"Carl Jackson","exchange":"613","open_price":"-54.04"}
{"time":"8","symbol":"SAFCO Mobile Desk Side File, Wire Frame","name":"Carl
Jackson","exchange":"613","open_price":"127.70"}
{"time":"9","symbol":"SAFCO Commercial Wire Shelving, Black","name":"Monica
Federle","exchange":"643","open_price":"-695.26"}
{"time":"10","symbol":"Xerox 198","name":"Dorothy
Badders","exchange":"678","open_price":"-226.36"}

JSON data sample:
{"time":"2016-07-28 10:40:31","symbol":"NTDOY","name":"NINTENDO CO LTD
ADR","exchange":"PNK","open_price":25.24}

CSV data sample:
1 Eldon Base for stackable storage shelf, platinum Muhammed MacIntyre 3
-213.25 38.94 35 Nunavut Storage & Organization 0.8


Topic df_meta messages:
{"cuid":"5869819fbba4a40a6e568488","file_name":"stock_20160728104030_update2.json","file_size":"912","file_owner":"vagrant","last_modified_timestamp":"2017-01-01
17:24:03.0","current_timestamp":"2017-01-01
17:24:34.037","current_timemillis":1483309474037,"stream_offset":"0","topic_sent":"stock","schema_subject":"test-value","schema_version":"1","status":"START"}
{"cuid":"5869819fbba4a40a6e568488","file_name":"stock_20160728104030_update2.json","file_size":"912","file_owner":"vagrant","last_modified_timestamp":"2017-01-01
17:24:03.0","current_timestamp":"2017-01-01
17:24:34.565","current_timemillis":1483309474565,"stream_offset":"912","topic_sent":"stock","schema_subject":"test-value","schema_version":"1","status":"END"}
{"cuid":"5869819fbba4a40a6e568488","file_name":"SampleCSVFile.csv","file_size":"1098","file_owner":"vagrant","last_modified_timestamp":"2016-12-29
21:53:15.0","current_timestamp":"2017-01-01
17:25:55.433","current_timemillis":1483309555433,"stream_offset":"0","topic_sent":"stock","schema_subject":"test-value","schema_version":"1","status":"START"}
{"cuid":"5869819fbba4a40a6e568488","file_name":"SampleCSVFile.csv","file_size":"1098","file_owner":"vagrant","last_modified_timestamp":"2016-12-29
21:53:15.0","current_timestamp":"2017-01-01
17:25:55.642","current_timemillis":1483309555642,"stream_offset":"1098","topic_sent":"stock","schema_subject":"test-value","schema_version":"1","status":"END"}

**Comment by SchubertZhu** [comment]
Please see the sample json file and csv file.

Regards,

Schubert
